{
  config,
  lib,
  pkgs,
  ...
}:
with lib;
let
  # Fcitx5 classicui theme (Material dark) for the clipboard/unicode
  # pickers. classicui has no corner-radius field — rounded corners
  # require 9-sliced background images — so the SVG sources under
  # ../../configs/fcitx5/theme are rendered to PNG at build time (classicui
  # loads PNG via cairo). Installed to share/fcitx5/themes/micro-material
  # (linked onto XDG_DATA_DIRS via pathsToLink "/share/fcitx5") and
  # selected by the classicui Theme= setting below.
  microFcitx5Theme = pkgs.runCommand "micro-fcitx5-theme" { nativeBuildInputs = [ pkgs.librsvg ]; } ''
    dst=$out/share/fcitx5/themes/micro-material
    mkdir -p "$dst"
    cp ${../../configs/fcitx5/theme/micro-material/theme.conf} "$dst/theme.conf"
    rsvg-convert -o "$dst/panel.png"     ${../../configs/fcitx5/theme/micro-material/panel.svg}
    rsvg-convert -o "$dst/highlight.png" ${../../configs/fcitx5/theme/micro-material/highlight.svg}
  '';
in
{
  config = {
    environment = {
      pathsToLink = [
        # fcitx5 classicui themes (micro-material) resolve via
        # XDG_DATA_DIRS/fcitx5/themes — link the fcitx5 data dir so the
        # fcitx5 user service finds the theme.
        "/share/fcitx5"
      ];
      systemPackages = [
        # Classicui theme for the fcitx5 clipboard/emoji pickers
        # (i18n.inputMethod adds fcitx5-with-addons itself).
        microFcitx5Theme
      ];
    };

    # Fcitx5 as a clipboard-history (Super+V) + unicode/emoji (Super+.)
    # picker — NOT for CJK text input. The only input method is the
    # built-in keyboard-us group; every IM-switching hotkey is disabled
    # in globalOptions so fcitx doesn't grab Ctrl+Space / Super+Space.
    # The pickers commit at the text caret over the Wayland input-method
    # protocol (waylandFrontend), so their triggers must reach the app —
    # niri must NOT bind Super+V / Super+. (see configs/niri/base.kdl).
    #
    # Config is generated by the core module: settings.globalOptions →
    # /etc/xdg/fcitx5/config, settings.addons.<name> →
    # /etc/xdg/fcitx5/conf/<name>.conf. Booleans are written as the
    # capitalized strings fcitx expects ("True"/"False"); an empty
    # attrset renders a bare section header (= empty list override).
    i18n = {
      inputMethod = {
        enable = mkDefault true;
        fcitx5 = {
          settings = {
            addons = {
              # Candidate window styling; selects the micro-material theme.
              classicui = {
                globalSection = {
                  DarkTheme = "micro-material";
                  Font = "Inter 11";
                  MenuFont = "Inter 11";
                  PerScreenDPI = "False";
                  Theme = "micro-material";
                  TrayFont = "Inter Bold 10";
                  "Vertical Candidate List" = "True";
                };
              };
              # Windows-11-style Super+V clipboard history; picking an
              # entry commits it through the input context (paste-at-cursor).
              clipboard = {
                globalSection = {
                  ClearPasswordAfter = 30;
                  IgnorePasswordFromPasswordManager = "True";
                  "Number of entries" = 30;
                  ShowPassword = "False";
                };
                sections = {
                  PastePrimaryKey = { }; # no paste-primary key
                  # Keysym MUST be uppercase V — fcitx normalizes letter
                  # keys to their uppercase keysym before matching.
                  TriggerKey = {
                    "0" = "Super+V";
                  };
                };
              };
              # Super+. searches symbols/emoji by Unicode name (Win+. style).
              unicode = {
                globalSection = { };
                sections = {
                  TriggerKey = {
                    "0" = "Super+period";
                  };
                };
              };
              # Keep the virtual keyboard alive across focus changes to
              # avoid re-pushing a keymap (xkbcomp journal spam) each time.
              waylandim = {
                globalSection = {
                  PersistentVirtualKeyboard = "True";
                };
              };
            };
            globalOptions = {
              # Add this block to control the candidate menu item count
              globalSection = {
                PageSize = 30;
              };
              # Disable IM trigger / group-switch hotkeys (single IM only) —
              # every "Hotkey/*Keys" entry below set to {} is disabled.
              # Candidate nav for both pickers: Up/Down = prev/next candidate,
              # Left/Right (+ Page_Up/Down) = paging.
              Behavior = {
                ShowInputMethodInformation = "False";
              };
              "Hotkey/ActivateKeys" = { };
              "Hotkey/AltTriggerKeys" = { };
              "Hotkey/DeactivateKeys" = { };
              "Hotkey/EnumerateBackwardKeys" = { };
              "Hotkey/EnumerateForwardKeys" = { };
              "Hotkey/EnumerateGroupBackwardKeys" = { };
              "Hotkey/EnumerateGroupForwardKeys" = { };
              "Hotkey/NextCandidate" = {
                "0" = "Down";
              };
              "Hotkey/NextPage" = {
                "0" = "Right";
                "1" = "Page_Down";
              };
              "Hotkey/PrevCandidate" = {
                "0" = "Up";
              };
              "Hotkey/PrevPage" = {
                "0" = "Left";
                "1" = "Page_Up";
              };
              "Hotkey/TriggerKeys" = { };
            };
          };
          # Wayland frontend: commit-at-caret via zwp_input_method_v2 and
          # leave GTK_IM_MODULE/QT_IM_MODULE unset so normal typing is not
          # routed through fcitx. clipboard/unicode/classicui/waylandim are
          # all in base fcitx5-with-addons, so no extra addons are needed.
          waylandFrontend = mkDefault true;
        };
        type = mkDefault "fcitx5";
      };
    };

    systemd = {
      user = {
        services = {
          # Fcitx5 input method: clipboard history (Super+V) + unicode/
          # emoji picker (Super+.). The core i18n.inputMethod module
          # installs fcitx5-with-addons and generates the config but does
          # not autostart it, so bind it to the graphical session here.
          # -D runs in the foreground (systemd tracks it); -r replaces a
          # stale instance after a compositor respawn.
          fcitx5 = {
            after = [ "graphical-session.target" ];
            description = "Fcitx5 input method (clipboard history + unicode/emoji picker)";
            partOf = [ "graphical-session.target" ];
            serviceConfig = {
              ExecStart = "${config.i18n.inputMethod.package}/bin/fcitx5 -D -r";
              Restart = "on-failure";
              RestartSec = 1;
            };
            wantedBy = [ "graphical-session.target" ];
          };
        };
      };
    };
  };
}
